FROM 459205453152.dkr.ecr.eu-central-1.amazonaws.com/f1app/base-builder:latest AS builder
WORKDIR /app

FROM node:22-alpine AS runner
WORKDIR /app

RUN apk add --no-cache curl

COPY --from=builder /app/apps/backend/ ./
COPY --from=builder /app/node_modules ./node_modules

RUN curl -o /app/apps/backend/global-bundle.pem \
    https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem

EXPOSE 3002
CMD ["npm", "run", "start:prod"]
