FROM 459205453152.dkr.ecr.eu-central-1.amazonaws.com/f1app/base-builder:latest AS builder
WORKDIR /app

FROM node:22-alpine AS runner
WORKDIR /app

RUN apk add --no-cache curl

COPY --from=builder /app/apps/backend .

RUN pwd
RUN ls

RUN curl -o global-bundle.pem https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem

EXPOSE 3002
CMD ["npm", "run", "start:prod"]
