FROM 459205453152.dkr.ecr.eu-central-1.amazonaws.com/f1app/base-builder:latest AS builder
WORKDIR /app

FROM node:22-alpine AS runner
WORKDIR /app

COPY --from=builder /app/apps/backend/ ./
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000
CMD ["npm", "run", "start:prod"]
