FROM node:22-slim

WORKDIR /app

RUN apt-get update && apt-get install -y procps

ENV NEXT_FORCE_SWC_WASM=1
ENV MONGODB_URI=mongodb://mongo:27017/f1seasons
ENV ERGAST_API_BASE=http://ergast.com/api/f1
ENV REDIS_URI=redis://redis:6379

# Copy the rest of the app source code
COPY . .

EXPOSE 3000
EXPOSE 3001
EXPOSE 3002
EXPOSE 6006

# Use turbo to run dev (or your own custom script)
CMD ["npm", "run", "dev"]