FROM node:22-alpine AS base-builder
WORKDIR /app

COPY package.json package-lock.json turbo.json ./
COPY apps/frontend/package.json ./apps/frontend/
COPY apps/backend/package.json ./apps/backend/
COPY packages/*/package.json ./packages/*/

RUN npm install

COPY . .

# Build everything (or you can build selectively in other stages)
RUN npx turbo run build
