services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"   # frontend
      - "3001:3001"   # docs
      - "3002:3002"   # backend
      - "6006:6006"   # storybook
    environment:
      - NODE_ENV=development
    command: npm run docker:startup

    volumes:
      - .:/app
      # exclude node_modules from the host to avoid conflicts:
      - node_modules:/app/node_modules

volumes:
  mongo-data:
  node_modules:
