import type { Metadata } from "next";
import "@repo/uikit/styles/index.css";
import { MainLayout } from "../components/MainLayout";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			data-theme="light"
			data-platform="desktop"
			data-brand="f1-app"
		>
			<MainLayout>{children}</MainLayout>
		</html>
	);
}
