name: Predeploy checkup
 
on:
  push:
    branches: ["main", "staging"]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  snyk:
    uses: ./.github/workflows/snyk-security.yml

  lint:
    uses: ./.github/workflows/lint.yml

