name: Lint and Test
 
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
 
jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
     TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
     TURBO_TEAM: ${{ vars.TURBO_TEAM }}
     TURBO_CACHE: remote:rw
     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
 
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
 
      - name: Install dependencies
        run: npm ci

      - name: Sentry login
        run: npx sentry-cli login --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }}
 
      - name: CI lint / test / build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: npm run ci

 