import type { Metadata } from "next";
import "@repo/uikit/styles/index.css";
import { cookies } from "next/headers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();
	const currentTheme = cookieStore.get("theme")?.value ?? "light";

	return (
		<html
			lang="en"
			data-theme={currentTheme}
			data-platform="desktop"
			data-brand="f1-app"
		>
			<body>{children}</body>
		</html>
	);
}
